#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  -s -lsqlite3 $(LDFLAGS)
OBJDIR_RELEASE = obj
DEP_RELEASE = 
OUT_RELEASE = bin/keylog

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/keydb.o $(OBJDIR_RELEASE)/src/keylog.o $(OBJDIR_RELEASE)/src/keyrecord.o

all: release

clean: clean_release

before_release: 
	test -d bin || mkdir -p bin
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/keydb.o: src/keydb.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/keydb.cpp -o $(OBJDIR_RELEASE)/src/keydb.o

$(OBJDIR_RELEASE)/src/keylog.o: src/keylog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/keylog.cpp -o $(OBJDIR_RELEASE)/src/keylog.o

$(OBJDIR_RELEASE)/src/keyrecord.o: src/keyrecord.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/keyrecord.cpp -o $(OBJDIR_RELEASE)/src/keyrecord.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_release after_release clean_release

